In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score,train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_recall_fscore_support, f1_score, roc_curve, roc_auc_score, RocCurveDisplay, auc
from collections import Counter
from sklearn import preprocessing
from sklearn.model_selection import RandomizedSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

def convert(data):
    number = preprocessing.LabelEncoder()
    data['operator'] = number.fit_transform(data.operator)
    data['methodReturn'] = number.fit_transform(data.methodReturn)
    data['isKilled'] = number.fit_transform(data.isKilled)
    return data

# Read in data and display first 5 rows
features = pd.read_csv('py_files/training_data.csv',encoding= 'unicode_escape')
#print(features)
#print('The shape of our features is:', features.shape)

#Convert string to float
features=convert(features)
print(features)
print('The shape of our features is:', features.shape) 

# Use numpy to convert to arrays
# Labels are the values we want to predict
labels = np.array(features['isKilled'])
# Remove the labels from the features
# axis 1 refers to the columns
features= features.drop('isKilled', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
features = np.array(features)

        DepthTree  NumSubclass  McCabe  LOC  DepthNested   CA  CE  \
0               2            0       1    3            1  364  16   
1               2            0       1    3            1  364  16   
2               2            0       1    3            1  364  16   
3               2            0       1    3            1  364  16   
4               2            0       1    3            1  364  16   
...           ...          ...     ...  ...          ...  ...  ..   
591808          3            0       1    3            1    1  11   
591809          2            0       1    3            1    1  11   
591810          3            0       1    3            1    1  11   
591811          1            0       1    3            1    1  11   
591812          2            0       1    3            1    1  11   

        Instability  numCovered  operator  methodReturn  numTestsCover  \
0             0.042          12         7             7             17   
1             0.042    

In [8]:
##Input test data
positive_prob = []
test = pd.read_csv('py_files/testing_data.csv',encoding= 'unicode_escape')

#Convert string to float
test=convert(test)

# ## Labels are the values we want to predict
test_labels = np.array(test['isKilled'])

# # Remove the labels from the features
# # axis 1 refers to the columns
test= test.drop('isKilled', axis = 1)
# # Saving feature names for later use
feature_list = list(test.columns)
# # Convert to numpy array
test = np.array(test)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.5,random_state=0)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)


(295906, 14) (295906,)
(295907, 14) (295907,)


In [20]:
logreg = LogisticRegression(solver='lbfgs')
logreg.fit(X_train, y_train)
y_pred_train_logreg = logreg.predict(X_test)
print(accuracy_score(y_test, y_pred_train_logreg))
print(confusion_matrix(y_test, y_pred_train_logreg))

y_pred_test = logreg.predict(test)

print(accuracy_score(test_labels, y_pred_test))
confusion = confusion_matrix(test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)
print(precision_recall_fscore_support(test_labels, y_pred_test, average='micro'))
print(f1_score(test_labels, y_pred_test, average='micro'))

0.9409882158921553
[[217779  17337]
 [   125  60666]]
0.8915766505939714
Confusion_matrix:
 [[76882 16100]
 [    0 55510]]
(0.8915766505939714, 0.8915766505939714, 0.8915766505939714, None)
0.8915766505939714


In [10]:
X1_train, X1_test, y1_train, y1_test = train_test_split(features, labels, test_size=0.3,random_state=0)
print (X1_train.shape, y1_train.shape)
print (X1_test.shape, y1_test.shape)

(414269, 14) (414269,)
(177544, 14) (177544,)


In [14]:
logreg = LogisticRegression()
logreg.fit(X1_train, y1_train)
y1_pred_train_logreg = logreg.predict(X1_test)
print(accuracy_score(y1_test, y1_pred_train_logreg))
print(confusion_matrix(y1_test, y1_pred_train_logreg))

y_pred_test = logreg.predict(test)

print(accuracy_score(test_labels, y_pred_test))
confusion = confusion_matrix(test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)
print(precision_recall_fscore_support(test_labels, y_pred_test, average='micro'))
print(f1_score(test_labels, y_pred_test, average='micro'))

0.9414060739872933
[[130824  10328]
 [    75  36317]]
0.891590119333028
Confusion_matrix:
 [[76884 16098]
 [    0 55510]]
(0.891590119333028, 0.891590119333028, 0.891590119333028, None)
0.891590119333028
