In [1]:
# Pandas is used for data manipulation
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score,train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_recall_fscore_support, f1_score, roc_curve, roc_auc_score, RocCurveDisplay, auc
from collections import Counter
from sklearn import preprocessing
from sklearn.model_selection import RandomizedSearchCV
from sklearn import svm

#def convert(data):
#    number = preprocessing.LabelEncoder()
#    data['operator'] = number.fit_transform(data.operator)
#    data['methodReturn'] = number.fit_transform(data.methodReturn)
#    data['isKilled'] = number.fit_transform(data.isKilled)
#    return data

# Read in data and display first 5 rows
features = pd.read_csv('py_files/training_data.csv',encoding= 'unicode_escape')
#print(features)
#print('The shape of our features is:', features.shape)
new_features= features.drop('methodReturn', axis = 1)
new_features= new_features.drop('operator', axis = 1)
#Convert string to float
#features=convert(features)
#print(features)
#print('The shape of our features is:', features.shape) 

# Use numpy to convert to arrays
# Labels are the values we want to predict
labels = np.array(new_features['isKilled'])
# Remove the labels from the features
# axis 1 refers to the columns
new_features= new_features.drop('isKilled', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
new_features = np.array(new_features)

In [2]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(new_features, labels, train_size=0.25)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

(147953, 12) (147953,)
(443860, 12) (443860,)


In [3]:
from sklearnex import patch_sklearn
patch_sklearn()

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [5]:
#Create a svm Classifier
clf = svm.SVC(kernel='linear',C=0.1) # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(C=0.1, kernel='linear')

In [6]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.20518406704816833


In [15]:
def convert(data):
    number = preprocessing.LabelEncoder()
    data['operator'] = number.fit_transform(data.operator)
    data['methodReturn'] = number.fit_transform(data.methodReturn)
    return data

features = pd.read_csv('py_files/training_data.csv',encoding= 'unicode_escape')
features=convert(features)
# Labels are the values we want to predict
labels = np.array(features['isKilled'])
features= features.drop('isKilled', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
features = np.array(features)

##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.5)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

clf = svm.SVC(kernel='sigmoid',coef0=1,C=0.01)
clf.fit(X_train, y_train)

test = pd.read_csv('py_files/testing_data.csv',encoding= 'unicode_escape')

#Convert string to float
test=convert(test)

# ## Labels are the values we want to predict
np_test_labels = np.array(test['isKilled'])

# # Remove the labels from the features
# # axis 1 refers to the columns
test= test.drop('isKilled', axis = 1)
# # Saving feature names for later use
feature_list = list(test.columns)
# # Convert to numpy array
np_test = np.array(test)
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

(295906, 14) (295906,)
(295907, 14) (295907,)
0.847378983379576
Confusion_matrix:
 [[79778 13204]
 [ 9459 46051]]


In [17]:
def convert(data):
    number = preprocessing.LabelEncoder()
    data['operator'] = number.fit_transform(data.operator)
    data['methodReturn'] = number.fit_transform(data.methodReturn)
    return data

features = pd.read_csv('py_files/training_data.csv',encoding= 'unicode_escape')
features=convert(features)
# Labels are the values we want to predict
labels = np.array(features['isKilled'])
features= features.drop('isKilled', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
features = np.array(features)

##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.5)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

clf = svm.SVC(kernel='rbf',gamma=5e-06,C=10)
clf.fit(X_train, y_train)

test = pd.read_csv('py_files/testing_data.csv',encoding= 'unicode_escape')

#Convert string to float
test=convert(test)

# ## Labels are the values we want to predict
np_test_labels = np.array(test['isKilled'])

# # Remove the labels from the features
# # axis 1 refers to the columns
test= test.drop('isKilled', axis = 1)
# # Saving feature names for later use
feature_list = list(test.columns)
# # Convert to numpy array
np_test = np.array(test)
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

(295906, 14) (295906,)
(295907, 14) (295907,)
0.837614147563505
Confusion_matrix:
 [[84750  8232]
 [15881 39629]]


In [18]:
from sklearn.svm import LinearSVC
def convert(data):
    number = preprocessing.LabelEncoder()
    data['operator'] = number.fit_transform(data.operator)
    data['methodReturn'] = number.fit_transform(data.methodReturn)
    return data

features = pd.read_csv('py_files/training_data.csv',encoding= 'unicode_escape')
features=convert(features)
# Labels are the values we want to predict
labels = np.array(features['isKilled'])
features= features.drop('isKilled', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
features = np.array(features)

##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.5)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

clf = svm.LinearSVC(dual=False) 
clf.fit(X_train, y_train)

test = pd.read_csv('py_files/testing_data.csv',encoding= 'unicode_escape')

#Convert string to float
test=convert(test)

# ## Labels are the values we want to predict
np_test_labels = np.array(test['isKilled'])

# # Remove the labels from the features
# # axis 1 refers to the columns
test= test.drop('isKilled', axis = 1)
# # Saving feature names for later use
feature_list = list(test.columns)
# # Convert to numpy array
np_test = np.array(test)
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)


(295906, 14) (295906,)
(295907, 14) (295907,)
0.638667402957735
Confusion_matrix:
 [[92449   533]
 [53122  2388]]


In [ ]:
from sklearn.svm import LinearSVC
def convert(data):
    number = preprocessing.LabelEncoder()
    data['operator'] = number.fit_transform(data.operator)
    data['methodReturn'] = number.fit_transform(data.methodReturn)
    return data

features = pd.read_csv('py_files/training_data.csv',encoding= 'unicode_escape')
features=convert(features)
# Labels are the values we want to predict
labels = np.array(features['isKilled'])
features= features.drop('isKilled', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)
# Convert to numpy array
features = np.array(features)

##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.5)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

clf = RandomForestClassifier(n_estimators = 250, random_state = 5,criterion="entropy")
clf.fit(X_train, y_train)

test = pd.read_csv('py_files/testing_data.csv',encoding= 'unicode_escape')

#Convert string to float
test=convert(test)

# ## Labels are the values we want to predict
np_test_labels = np.array(test['isKilled'])

# # Remove the labels from the features
# # axis 1 refers to the columns
test= test.drop('isKilled', axis = 1)
# # Saving feature names for later use
feature_list = list(test.columns)
# # Convert to numpy array
np_test = np.array(test)
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

In [12]:
#Create a svm Classifier
clf = svm.SVC(kernel='linear',C=0.1) # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(C=0.1, kernel='linear')

In [13]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.7944487000405533


In [14]:
#Create a svm Classifier
clf = svm.SVC(kernel='linear',C=1.0) # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [15]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.7944487000405533


In [16]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.4)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

(236725, 14) (236725,)
(355088, 14) (355088,)


In [17]:
#Create a svm Classifier
clf = svm.SVC(kernel='linear',C=1.0) # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [18]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.7008797819132159


In [19]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=1.0,gamma=0.1) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(147953, 14) (147953,)
(443860, 14) (443860,)


SVC(gamma=0.1)

In [20]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9404609561573469


In [21]:
#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=1.0,gamma=1.0) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(gamma=1.0)

In [22]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.8519127652863515


In [23]:
#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=1.0,gamma=10.0) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(gamma=10.0)

In [24]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.8328572072275041


In [25]:
#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=1.0,gamma=0.01) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(gamma=0.01)

In [26]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9468931645113324


In [32]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm

#Hyper parameter tuning
#gamma for rbf
gamma = [0.001,0.005,0.01,0.05,0.1]
C = [0.01,0.1,1.0,10]
kernel=['rbf']
# Create the  grid
grid = {'gamma':gamma,'C':C,'kernel':kernel}
print(grid)

# Import the model we are using
sv = svm.SVC()
# Use the grid to search for best hyperparameters
# First create the base model to tune
svm_grid = GridSearchCV(estimator = sv, param_grid = grid)
svm_grid.fit(X_train, y_train)
print(svm_grid.best_params_)

{'gamma': [0.001, 0.005, 0.01, 0.05, 0.1], 'C': [0.01, 0.1, 1.0, 10], 'kernel': ['rbf']}
{'C': 1.0, 'gamma': 0.01, 'kernel': 'rbf'}


In [33]:
#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=1.0,gamma=0.01) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(gamma=0.01)

In [34]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9468931645113324


In [5]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.3)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=1.0,gamma=0.01) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(177543, 14) (177543,)
(414270, 14) (414270,)


SVC(gamma=0.01)

In [6]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9481328602119391


In [7]:
test = pd.read_csv('py_files/testing_data.csv',encoding= 'unicode_escape')

#Convert string to float
test=convert(test)

# ## Labels are the values we want to predict
np_test_labels = np.array(test['isKilled'])

# # Remove the labels from the features
# # axis 1 refers to the columns
test= test.drop('isKilled', axis = 1)
# # Saving feature names for later use
feature_list = list(test.columns)
# # Convert to numpy array
np_test = np.array(test)
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)
print(precision_recall_fscore_support(np_test_labels, y_pred_test, average='micro'))
print(f1_score(np_test_labels, y_pred_test, average='micro'))

0.4710624141367885
Confusion_matrix:
 [[17112 75870]
 [ 2673 52837]]
(0.4710624141367885, 0.4710624141367885, 0.4710624141367885, None)
0.4710624141367885


In [39]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=1.0,gamma=0.01) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(147953, 14) (147953,)
(443860, 14) (443860,)


SVC(gamma=0.01)

In [40]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.4713115858093365
Confusion_matrix:
 [[17120 75862]
 [ 2644 52866]]


In [41]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.7)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=1.0,gamma=0.01) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(414269, 14) (414269,)
(177544, 14) (177544,)


SVC(gamma=0.01)

In [42]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9534875861758212


In [43]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.473271287342079
Confusion_matrix:
 [[17278 75704]
 [ 2511 52999]]


In [44]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.7)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=1.0,gamma=0.1) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(414269, 14) (414269,)
(177544, 14) (177544,)


SVC(gamma=0.1)

In [45]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9512289911233271


In [46]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.42432588961021467
Confusion_matrix:
 [[ 7863 85119]
 [  364 55146]]


In [47]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=0.1,gamma=0.01) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(147953, 14) (147953,)
(443860, 14) (443860,)


SVC(C=0.1, gamma=0.01)

In [48]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9353602487270761


In [49]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.46522371575573096
Confusion_matrix:
 [[16848 76134]
 [ 3276 52234]]


In [50]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=0.1,gamma=0.001) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(147953, 14) (147953,)
(443860, 14) (443860,)


SVC(C=0.1, gamma=0.001)

In [51]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9295994232415626


In [52]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.48270613905126203
Confusion_matrix:
 [[21918 71064]
 [ 5750 49760]]


In [53]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=0.1,gamma=0.0001) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(147953, 14) (147953,)
(443860, 14) (443860,)


SVC(C=0.1, gamma=0.0001)

In [54]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9161605010588925


In [55]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.7406661638337418
Confusion_matrix:
 [[68069 24913]
 [13596 41914]]


In [56]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=0.01,gamma=0.0001) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(147953, 14) (147953,)
(443860, 14) (443860,)


SVC(C=0.01, gamma=0.0001)

In [57]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.8978236380840806


In [58]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.724368989575196
Confusion_matrix:
 [[66687 26295]
 [14634 40876]]


In [59]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=1.0,gamma=0.0001) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(147953, 14) (147953,)
(443860, 14) (443860,)


SVC(gamma=0.0001)

In [60]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9265489118190421


In [61]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.7564380572690784
Confusion_matrix:
 [[67659 25323]
 [10844 44666]]


In [65]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=5.0,gamma=0.0001) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(147953, 14) (147953,)
(443860, 14) (443860,)


SVC(C=5.0, gamma=0.0001)

In [66]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9303068535123687


In [67]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.7590307895374835
Confusion_matrix:
 [[66015 26967]
 [ 8815 46695]]


In [68]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=5.0,gamma=0.00001) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(147953, 14) (147953,)
(443860, 14) (443860,)


SVC(C=5.0, gamma=1e-05)

In [69]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9104267111251295


In [70]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.8346644937100989
Confusion_matrix:
 [[83227  9755]
 [14796 40714]]


In [71]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=5.0,gamma=0.000001) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(147953, 14) (147953,)
(443860, 14) (443860,)


SVC(C=5.0, gamma=1e-06)

In [72]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.8846798540080205


In [73]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.8083263744848207
Confusion_matrix:
 [[86262  6720]
 [21742 33768]]


In [16]:
##Validation set create training and testing vars
#X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
#print (X_train.shape, y_train.shape)
#print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=10.0,gamma=0.00001) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(C=10.0, gamma=1e-05)

In [17]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9106767899788222


In [18]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.8379306629313363
Confusion_matrix:
 [[83714  9268]
 [14798 40712]]


In [9]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=50.0,gamma=0.00001) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

(147953, 14) (147953,)
(443860, 14) (443860,)


SVC(C=50.0, gamma=1e-05)

In [10]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

Accuracy: 0.9169648087234714


In [11]:
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

0.8371225385879374
Confusion_matrix:
 [[83811  9171]
 [15015 40495]]


In [12]:
#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=100.0,gamma=0.00001) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(C=100.0, gamma=1e-05)

In [13]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

Accuracy: 0.9183954400036047
0.8397085364868141
Confusion_matrix:
 [[83808  9174]
 [14628 40882]]


In [14]:
#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=100.0,gamma=0.000001) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(C=100.0, gamma=1e-06)

In [15]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

Accuracy: 0.8939981075113774
0.8158486652479595
Confusion_matrix:
 [[86286  6696]
 [20649 34861]]


In [19]:
#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=1000.0,gamma=0.00001) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

SVC(C=1000.0, gamma=1e-05)

In [20]:
#Predict the response for test dataset
y_pred = clf.predict(X_test)

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",accuracy_score(y_test, y_pred))

y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)

Accuracy: 0.9238633803451539
0.8247380330253482
Confusion_matrix:
 [[81970 11012]
 [15013 40497]]


In [21]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm

#Hyper parameter tuning
#gamma for rbf
gamma = [0.000001,0.000005,0.00001,0.00005,0.0001,0.0005]
C = [0.01,0.1,1.0,10,15,50,100,200,500]
kernel=['rbf']
# Create the  grid
grid = {'gamma':gamma,'C':C,'kernel':kernel}
print(grid)

# Import the model we are using
sv = svm.SVC()
# Use the grid to search for best hyperparameters
# First create the base model to tune
svm_grid = GridSearchCV(estimator = sv, param_grid = grid)
svm_grid.fit(X_train, y_train)
print(svm_grid.best_params_)

{'gamma': [1e-06, 5e-06, 1e-05, 5e-05, 0.0001, 0.0005], 'C': [0.01, 0.1, 1.0, 10, 15, 50, 100, 200, 500], 'kernel': ['rbf']}
{'C': 50, 'gamma': 0.0005, 'kernel': 'rbf'}


In [22]:
#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=50.0,gamma=0.0005) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)


y_pred = svm_grid.predict(X_test)
y_pred_test = svm_grid.predict(np_test)
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))

***Validation accuracy***
0.9446447077907448
***Test accuracy***
0.4844301376505132


In [23]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm

#Hyper parameter tuning
#gamma for rbf
gamma = [0.000001,0.000005,0.00001,0.00005]
C = [0.01,0.1,1.0,10,15,50,100,200,500]
kernel=['rbf']
# Create the  grid
grid = {'gamma':gamma,'C':C,'kernel':kernel}
print(grid)

# Import the model we are using
sv = svm.SVC()
# Use the grid to search for best hyperparameters
# First create the base model to tune
svm_grid = GridSearchCV(estimator = sv, param_grid = grid)
svm_grid.fit(X_train, y_train)
print(svm_grid.best_params_)

{'gamma': [1e-06, 5e-06, 1e-05, 5e-05], 'C': [0.01, 0.1, 1.0, 10, 15, 50, 100, 200, 500], 'kernel': ['rbf']}
{'C': 500, 'gamma': 5e-05, 'kernel': 'rbf'}


In [27]:
#Create a svm Classifier
clf = svm.SVC(kernel='rbf',C=500.0,gamma=0.00005) # rbf Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)


y_pred = clf.predict(X_test)
y_pred_test = clf.predict(np_test)
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))

***Validation accuracy***
0.9353692605776596
***Test accuracy***
0.5598416076286938


In [28]:
#Create a svm Classifier
clf_1 = svm.SVC(kernel='rbf',C=500.0,gamma=0.00001) # rbf Kernel

#Train the model using the training sets
clf_1.fit(X_train, y_train)


y_pred = clf_1.predict(X_test)
y_pred_test = clf_1.predict(np_test)
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))

***Validation accuracy***
0.9223201009327265
***Test accuracy***
0.8351628370551949


In [29]:
#Create a svm Classifier
clf_2 = svm.SVC(kernel='rbf',C=100.0,gamma=0.00001) # rbf Kernel

#Train the model using the training sets
clf_2.fit(X_train, y_train)

y_pred = clf_2.predict(X_test)
y_pred_test = clf_2.predict(np_test)
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))

***Validation accuracy***
0.9183954400036047
***Test accuracy***
0.8397085364868141


In [30]:
#Create a svm Classifier
clf_2 = svm.SVC(kernel='rbf',C=10.0,gamma=0.00001) # rbf Kernel

#Train the model using the training sets
clf_2.fit(X_train, y_train)

y_pred = clf_2.predict(X_test)
y_pred_test = clf_2.predict(np_test)
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))

***Validation accuracy***
0.9106767899788222
***Test accuracy***
0.8379306629313363


In [31]:
#Create a svm Classifier
clf_2 = svm.SVC(kernel='rbf',C=1.0,gamma=0.00001) # rbf Kernel

#Train the model using the training sets
clf_2.fit(X_train, y_train)

y_pred = clf_2.predict(X_test)
y_pred_test = clf_2.predict(np_test)
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))

***Validation accuracy***
0.9028139503447032
***Test accuracy***
0.8230073000565687


In [32]:
#Create a svm Classifier
clf_2 = svm.SVC(kernel='rbf',C=0.1,gamma=0.00001) # rbf Kernel

#Train the model using the training sets
clf_2.fit(X_train, y_train)

y_pred = clf_2.predict(X_test)
y_pred_test = clf_2.predict(np_test)
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))

***Validation accuracy***
0.892326409228135
***Test accuracy***
0.8090132801767098


In [33]:
#Create a svm Classifier
clf_2 = svm.SVC(kernel='rbf',C=0.01,gamma=0.00001) # rbf Kernel

#Train the model using the training sets
clf_2.fit(X_train, y_train)

y_pred = clf_2.predict(X_test)
y_pred_test = clf_2.predict(np_test)
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))

***Validation accuracy***
0.8748366602081737
***Test accuracy***
0.7835371602510572


In [34]:
gamma = [0.000001,0.000005,0.00005,0.0001,0.001]
C = [0.01,0.1,1.0,10,100,500]
for i in gamma:
    for j in C:
        clf_grid = svm.SVC(kernel='rbf',C=j,gamma=i)
        clf_grid.fit(X_train, y_train)
        y_pred = clf_grid.predict(X_test)
        y_pred_test = clf_grid.predict(np_test)
        print("For gamma:", i," for C:",j)
        print("***Validation accuracy***")
        print(accuracy_score(y_test, y_pred))
        print("***Test accuracy***")
        print(accuracy_score(np_test_labels, y_pred_test))

For gamma: 1e-06  for C: 0.01
***Validation accuracy***
0.8526922903618258
***Test accuracy***
0.7552932144492632
For gamma: 1e-06  for C: 0.1
***Validation accuracy***
0.8655972603974226
***Test accuracy***
0.7731729655469655
For gamma: 1e-06  for C: 1.0
***Validation accuracy***
0.8780674086423647
***Test accuracy***
0.798709694798373
For gamma: 1e-06  for C: 10
***Validation accuracy***
0.8870409588609021
***Test accuracy***
0.8087775772432185
For gamma: 1e-06  for C: 100
***Validation accuracy***
0.8939981075113774
***Test accuracy***
0.8158486652479595
For gamma: 1e-06  for C: 500
***Validation accuracy***
0.8986572342630559
***Test accuracy***
0.8216334886727904
For gamma: 5e-06  for C: 0.01
***Validation accuracy***
0.8677691163880503
***Test accuracy***
0.7855237992619131
For gamma: 5e-06  for C: 0.1
***Validation accuracy***
0.8840828189068626
***Test accuracy***
0.8056191579344342
For gamma: 5e-06  for C: 1.0
***Validation accuracy***
0.8967467219393502
***Test accuracy***
0.

In [35]:
gamma = [0.0000025,0.000025]
C = [0.01,0.1,1.0,10,100,500]
for i in gamma:
    for j in C:
        clf_grid = svm.SVC(kernel='rbf',C=j,gamma=i)
        clf_grid.fit(X_train, y_train)
        y_pred = clf_grid.predict(X_test)
        y_pred_test = clf_grid.predict(np_test)
        print("For gamma:", i," for C:",j)
        print("***Validation accuracy***")
        print(accuracy_score(y_test, y_pred))
        print("***Test accuracy***")
        print(accuracy_score(np_test_labels, y_pred_test))

For gamma: 2.5e-06  for C: 0.01
***Validation accuracy***
0.8599333123056819
***Test accuracy***
0.7655227217627886
For gamma: 2.5e-06  for C: 0.1
***Validation accuracy***
0.8765984769972514
***Test accuracy***
0.79715405543733
For gamma: 2.5e-06  for C: 1.0
***Validation accuracy***
0.8885324201324742
***Test accuracy***
0.8091883737844463
For gamma: 2.5e-06  for C: 10
***Validation accuracy***
0.8972491326093813
***Test accuracy***
0.819963365029766
For gamma: 2.5e-06  for C: 100
***Validation accuracy***
0.9033862028567566
***Test accuracy***
0.8284688737440401
For gamma: 2.5e-06  for C: 500
***Validation accuracy***
0.909334024241878
***Test accuracy***
0.8257683915631818
For gamma: 2.5e-05  for C: 0.01
***Validation accuracy***
0.8831185508944261
***Test accuracy***
0.7547814023651106
For gamma: 2.5e-05  for C: 0.1
***Validation accuracy***
0.9015815797774073
***Test accuracy***
0.7809780998302939
For gamma: 2.5e-05  for C: 1.0
***Validation accuracy***
0.9121772631009778
***Test

In [37]:
gamma = [0.0000075]
C = [0.01,0.1,1.0,10,100,500]
for i in gamma:
    for j in C:
        clf_grid = svm.SVC(kernel='rbf',C=j,gamma=i)
        clf_grid.fit(X_train, y_train)
        y_pred = clf_grid.predict(X_test)
        y_pred_test = clf_grid.predict(np_test)
        print("For gamma:", i," for C:",j)
        print("***Validation accuracy***")
        print(accuracy_score(y_test, y_pred))
        print("***Test accuracy***")
        print(accuracy_score(np_test_labels, y_pred_test))

For gamma: 7.5e-06  for C: 0.01
***Validation accuracy***
0.8723764249988735
***Test accuracy***
0.7894027961102281
For gamma: 7.5e-06  for C: 0.1
***Validation accuracy***
0.8891249493083405
***Test accuracy***
0.8079896560084044
For gamma: 7.5e-06  for C: 1.0
***Validation accuracy***
0.9016153742170955
***Test accuracy***
0.819613177814293
For gamma: 7.5e-06  for C: 10
***Validation accuracy***
0.9094601901500473
***Test accuracy***
0.8360181019852921
For gamma: 7.5e-06  for C: 100
***Validation accuracy***
0.9153336637678547
***Test accuracy***
0.8326307141125447
For gamma: 7.5e-06  for C: 500
***Validation accuracy***
0.9188257558689676
***Test accuracy***
0.8353446650324596


In [38]:
gamma = [0.000009,0.00009]
C = [0.01,0.1,1.0,10,100,500]
for i in gamma:
    for j in C:
        clf_grid = svm.SVC(kernel='rbf',C=j,gamma=i)
        clf_grid.fit(X_train, y_train)
        y_pred = clf_grid.predict(X_test)
        y_pred_test = clf_grid.predict(np_test)
        print("For gamma:", i," for C:",j)
        print("***Validation accuracy***")
        print(accuracy_score(y_test, y_pred))
        print("***Test accuracy***")
        print(accuracy_score(np_test_labels, y_pred_test))

For gamma: 9e-06  for C: 0.01
***Validation accuracy***
0.8735907718650024
***Test accuracy***
0.7837526600759637
For gamma: 9e-06  for C: 0.1
***Validation accuracy***
0.8896273599783716
***Test accuracy***
0.8081916870942543
For gamma: 9e-06  for C: 1.0
***Validation accuracy***
0.9025616185283648
***Test accuracy***
0.8213573795221292
For gamma: 9e-06  for C: 10
***Validation accuracy***
0.909895011940702
***Test accuracy***
0.8366713358295397
For gamma: 9e-06  for C: 100
***Validation accuracy***
0.9180146893164511
***Test accuracy***
0.8370215230450125
For gamma: 9e-06  for C: 500
***Validation accuracy***
0.9206258730230252
***Test accuracy***
0.8384424750154891
For gamma: 9e-05  for C: 0.01
***Validation accuracy***
0.896769251565809
***Test accuracy***
0.7335614039813593
For gamma: 9e-05  for C: 0.1
***Validation accuracy***
0.9152615689631866
***Test accuracy***
0.7422150688252566
For gamma: 9e-05  for C: 1.0
***Validation accuracy***
0.9252917586626414
***Test accuracy***
0.7

In [41]:
gamma = [0.000015]
C = [0.01,0.1,1.0,10,100,500]
for i in gamma:
    for j in C:
        clf_grid = svm.SVC(kernel='rbf',C=j,gamma=i)
        clf_grid.fit(X_train, y_train)
        y_pred = clf_grid.predict(X_test)
        y_pred_test = clf_grid.predict(np_test)
        print("For gamma:", i," for C:",j)
        print("***Validation accuracy***")
        print(accuracy_score(y_test, y_pred))
        print("***Test accuracy***")
        print(accuracy_score(np_test_labels, y_pred_test))

For gamma: 1.5e-05  for C: 0.01
***Validation accuracy***
0.8787680800252332
***Test accuracy***
0.7823855830617138
For gamma: 1.5e-05  for C: 0.1
***Validation accuracy***
0.8963839949533636
***Test accuracy***
0.7988847884061094
For gamma: 1.5e-05  for C: 1.0
***Validation accuracy***
0.90918532870725
***Test accuracy***
0.8220846914311882
For gamma: 1.5e-05  for C: 10
***Validation accuracy***
0.9164263506511062
***Test accuracy***
0.8347924467311371
For gamma: 1.5e-05  for C: 100
***Validation accuracy***
0.9224462668408958
***Test accuracy***
0.839519974140021
For gamma: 1.5e-05  for C: 500
***Validation accuracy***
0.9256094263957103
***Test accuracy***
0.8211082078495812


### Sigmoid kernel

In [42]:
clf = svm.SVC(kernel='sigmoid',coef0=0.0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred_test = clf.predict(np_test)
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))

***Validation accuracy***
0.7955977109899518
***Test accuracy***
0.628505239339493


In [43]:
clf = svm.SVC(kernel='sigmoid',coef0=1.0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred_test = clf.predict(np_test)
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))

***Validation accuracy***
0.7951944306763394
***Test accuracy***
0.6270438811518466


In [40]:
C = [0.00001, 0.001,0.01,0.1,0.0,1.0,10,100]
for i in C:
        clf_grid = svm.SVC(kernel='sigmoid',coef0=i)
        clf_grid.fit(X_train, y_train)
        y_pred = clf_grid.predict(X_test)
        y_pred_test = clf_grid.predict(np_test)
        print("For coeff:",i)
        print("***Validation accuracy***")
        print(accuracy_score(y_test, y_pred))
        print("***Test accuracy***")
        print(accuracy_score(np_test_labels, y_pred_test))

For gamma: 1e-05  for C: 500
***Validation accuracy***
0.7955977109899518
***Test accuracy***
0.628505239339493
For gamma: 0.001  for C: 500
***Validation accuracy***
0.7955977109899518
***Test accuracy***
0.628505239339493
For gamma: 0.01  for C: 500
***Validation accuracy***
0.7955977109899518
***Test accuracy***
0.628505239339493
For gamma: 0.1  for C: 500
***Validation accuracy***
0.7955458928490966
***Test accuracy***
0.6282830051450583
For gamma: 1.0  for C: 500
***Validation accuracy***
0.7951944306763394
***Test accuracy***
0.6270438811518466
For gamma: 10  for C: 500
***Validation accuracy***
0.9129748118776191
***Test accuracy***
0.8316676992699944
For gamma: 100  for C: 500
***Validation accuracy***
0.20505114225206147
***Test accuracy***
0.3732456967378714


In [44]:
clf_grid = svm.SVC(kernel='sigmoid',coef0=10, C=10)
clf_grid.fit(X_train, y_train)
y_pred = clf_grid.predict(X_test)
y_pred_test = clf_grid.predict(np_test)
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))

***Validation accuracy***
0.9370184292344433
***Test accuracy***
0.8866672952078226


In [45]:
coeff = [0.01,0.1,0,1.0,10,100]
C = [0.01,0.1,1.0,10,50,100]
for i in coeff:
    for j in C:
        clf_grid = svm.SVC(kernel='sigmoid',coef0=i,C=j)
        clf_grid.fit(X_train, y_train)
        y_pred = clf_grid.predict(X_test)
        y_pred_test = clf_grid.predict(np_test)
        print("For coeff:", i," for C:",j)
        print("***Validation accuracy***")
        print(accuracy_score(y_test, y_pred))
        print("***Test accuracy***")
        print(accuracy_score(np_test_labels, y_pred_test))

For coeff: 0.01  for C: 0.01
***Validation accuracy***
0.10599288063803902
***Test accuracy***
0.2007986962260593
For coeff: 0.01  for C: 0.1
***Validation accuracy***
0.7954219799035732
***Test accuracy***
0.627966489777227
For coeff: 0.01  for C: 1.0
***Validation accuracy***
0.7955977109899518
***Test accuracy***
0.628505239339493
For coeff: 0.01  for C: 10
***Validation accuracy***
0.7955999639525977
***Test accuracy***
0.628336880101285
For coeff: 0.01  for C: 50
***Validation accuracy***
0.7955864461767224
***Test accuracy***
0.6282830051450583
For coeff: 0.01  for C: 100
***Validation accuracy***
0.7955864461767224
***Test accuracy***
0.6282830051450583
For coeff: 0.1  for C: 0.01
***Validation accuracy***
0.10676339386292975
***Test accuracy***
0.20287961641031166
For coeff: 0.1  for C: 0.1
***Validation accuracy***
0.7954219799035732
***Test accuracy***
0.627966489777227
For coeff: 0.1  for C: 1.0
***Validation accuracy***
0.7955458928490966
***Test accuracy***
0.6282830051450

In [47]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.7)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

clf_1 = svm.SVC(kernel='sigmoid',coef0=10,C=10)
clf_1.fit(X_train, y_train)
y_pred = clf_1.predict(X_test)
y_pred_test = clf_1.predict(np_test)
print("Sigmoid with 0.5 train set")
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))
print(confusion_matrix(y_test, y_pred))
print(confusion_matrix(np_test_labels, y_pred_test))


clf_2 = svm.SVC(kernel='rbf',gamma=0.00001,C=100)
clf_2.fit(X_train, y_train)
y_pred = clf_2.predict(X_test)
y_pred_test = clf_2.predict(np_test)
print("Gaussian with 0.5 train set")
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))
print(confusion_matrix(y_test, y_pred))
print(confusion_matrix(np_test_labels, y_pred_test))

(414269, 14) (414269,)
(177544, 14) (177544,)
Sigmoid with 0.5 train set
***Validation accuracy***
0.8588518902356599
***Test accuracy***
0.741292460199876
[[137887   3288]
 [ 21772  14597]]
[[87587  5395]
 [33021 22489]]
Gaussian with 0.5 train set
***Validation accuracy***
0.9219348443202812
***Test accuracy***
0.8461331250168359
[[134284   6891]
 [  6969  29400]]
[[83376  9606]
 [13242 42268]]


In [48]:
##Validation set create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.7)
print (X_train.shape, y_train.shape)
print (X_test.shape, y_test.shape)

clf_1 = svm.SVC(kernel='sigmoid',coef0=10,C=1)
clf_1.fit(X_train, y_train)
y_pred = clf_1.predict(X_test)
y_pred_test = clf_1.predict(np_test)
print("Sigmoid with 0.5 train set")
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))
print(confusion_matrix(y_test, y_pred))
print(confusion_matrix(np_test_labels, y_pred_test))


clf_2 = svm.SVC(kernel='rbf',gamma=0.00001,C=10)
clf_2.fit(X_train, y_train)
y_pred = clf_2.predict(X_test)
y_pred_test = clf_2.predict(np_test)
print("Gaussian with 0.5 train set")
print("***Validation accuracy***")
print(accuracy_score(y_test, y_pred))
print("***Test accuracy***")
print(accuracy_score(np_test_labels, y_pred_test))
print(confusion_matrix(y_test, y_pred))
print(confusion_matrix(np_test_labels, y_pred_test))

(414269, 14) (414269,)
(177544, 14) (177544,)
Sigmoid with 0.5 train set
***Validation accuracy***
0.8529378632902267
***Test accuracy***
0.7335277321337177
[[138148   2989]
 [ 23121  13286]]
[[88099  4883]
 [34686 20824]]
Gaussian with 0.5 train set
***Validation accuracy***
0.9162799080791241
***Test accuracy***
0.8373178353042589
[[134638   6499]
 [  8365  28042]]
[[83340  9642]
 [14515 40995]]


In [57]:
##Validation set create training and testing vars
validation_accuracy  = 0.0
test_accuracy = 0.0
for i in range(1,10):
    X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.25)
   # print (X_train.shape, y_train.shape)
   # print (X_test.shape, y_test.shape)

    clf_1 = svm.SVC(kernel='sigmoid',coef0=10,C=10)
    clf_1.fit(X_train, y_train)
    y_pred = clf_1.predict(X_test)
    y_pred_test = clf_1.predict(np_test)
    val = accuracy_score(y_test, y_pred)
    tes = accuracy_score(np_test_labels, y_pred_test)
    validation_accuracy = (validation_accuracy + val)
    test_accuracy = (test_accuracy + tes)
validation_accuracy = validation_accuracy/10
test_accuracy =test_accuracy/10
print("***Average validation accuracy***")
print(validation_accuracy)
print("***Average test accuracy***")
print(test_accuracy)

***Average validation accuracy***
0.8338345424232866
***Average test accuracy***
0.7752276216900574


In [58]:
##Validation set create training and testing vars
validation_accuracy  = 0.0
test_accuracy = 0.0
for i in range(1,10):
    X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.9)
   # print (X_train.shape, y_train.shape)
   # print (X_test.shape, y_test.shape)

    clf_1 = svm.SVC(kernel='sigmoid',coef0=10,C=10)
    clf_1.fit(X_train, y_train)
    y_pred = clf_1.predict(X_test)
    y_pred_test = clf_1.predict(np_test)
    val = accuracy_score(y_test, y_pred)
    tes = accuracy_score(np_test_labels, y_pred_test)
    validation_accuracy = (validation_accuracy + val)
    test_accuracy = (test_accuracy + tes)
validation_accuracy = validation_accuracy/10
test_accuracy =test_accuracy/10
print("***Average validation accuracy***")
print(validation_accuracy)
print("***Average test accuracy***")
print(test_accuracy)

***Average validation accuracy***
0.7668801324727113
***Average test accuracy***
0.6595223985130512


In [61]:
##Validation set create training and testing vars
validation_accuracy  = 0.0
test_accuracy = 0.0
for i in range(1,10):
    X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.75)
   # print (X_train.shape, y_train.shape)
   # print (X_test.shape, y_test.shape)

    clf_1 = svm.SVC(kernel='sigmoid',coef0=10,C=10)
    clf_1.fit(X_train, y_train)
    y_pred = clf_1.predict(X_test)
    y_pred_test = clf_1.predict(np_test)
    val = accuracy_score(y_test, y_pred)
    tes = accuracy_score(np_test_labels, y_pred_test)
    validation_accuracy = (validation_accuracy + val)
    test_accuracy = (test_accuracy + tes)
validation_accuracy = validation_accuracy/10
test_accuracy =test_accuracy/10
print("***Average validation accuracy***")
print(validation_accuracy)
print("***Average test accuracy***")
print(test_accuracy)

***Average validation accuracy***
0.7700596131229978
***Average test accuracy***
0.6649213425639092


In [60]:
##Validation set create training and testing vars
validation_accuracy  = 0.0
test_accuracy = 0.0
for i in range(1,10):
    X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=0.5)
   # print (X_train.shape, y_train.shape)
   # print (X_test.shape, y_test.shape)

    clf_1 = svm.SVC(kernel='sigmoid',coef0=10,C=10)
    clf_1.fit(X_train, y_train)
    y_pred = clf_1.predict(X_test)
    y_pred_test = clf_1.predict(np_test)
    val = accuracy_score(y_test, y_pred)
    tes = accuracy_score(np_test_labels, y_pred_test)
    validation_accuracy = (validation_accuracy + val)
    test_accuracy = (test_accuracy + tes)
validation_accuracy = validation_accuracy/10
test_accuracy =test_accuracy/10
print("***Average validation accuracy***")
print(validation_accuracy)
print("***Average test accuracy***")
print(test_accuracy)

## Sigmoid grid search for 0.5 train size - 20 samples

In [8]:
##Validation set create training and testing vars
size = [0.5]
for i in size:
    validation_accuracy  = 0.0
    test_accuracy = 0.0
    for j in range(1,20):
        X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=i)
        coeff = [0.01,0.1,0,1.0,10]
        C = [0.01,0.1,1.0,10,100]
        for k in coeff:
            for l in C:
                clf_grid = svm.SVC(kernel='sigmoid',coef0=k,C=l)
                clf_grid.fit(X_train, y_train)
                y_pred = clf_grid.predict(X_test)
                y_pred_test = clf_grid.predict(np_test)
                print("For sample:",j, " For coeff:", k," for C:",l)
                print("***Validation accuracy***")
                print(accuracy_score(y_test, y_pred))
                print("***Test accuracy***")
                print(accuracy_score(np_test_labels, y_pred_test))

For sample: 1  For coeff: 0.01  for C: 0.01
***Validation accuracy***
0.7959831974235149
***Test accuracy***
0.6271112248471298
For sample: 1  For coeff: 0.01  for C: 0.1
***Validation accuracy***
0.7963211414397091
***Test accuracy***
0.628505239339493
For sample: 1  For coeff: 0.01  for C: 1.0
***Validation accuracy***
0.06313470110541487
***Test accuracy***
0.12878808285968268
For sample: 1  For coeff: 0.01  for C: 10
***Validation accuracy***
0.06306373286201408
***Test accuracy***
0.12876114538156938
For sample: 1  For coeff: 0.01  for C: 100
***Validation accuracy***
0.8568671913810758
***Test accuracy***
0.7385919780190179
For sample: 1  For coeff: 0.1  for C: 0.01
***Validation accuracy***
0.7959831974235149
***Test accuracy***
0.6270573498909032
For sample: 1  For coeff: 0.1  for C: 0.1
***Validation accuracy***
0.7962772087176039
***Test accuracy***
0.6282830051450583
For sample: 1  For coeff: 0.1  for C: 1.0
***Validation accuracy***
0.06272240940565786
***Test accuracy***
0

## Gaussian grid search for 0.5 train size - 20 samples

In [9]:
##Validation set create training and testing vars
size = [0.5]
for i in size:
    validation_accuracy  = 0.0
    test_accuracy = 0.0
    for j in range(1,20):
        X_train, X_test, y_train, y_test = train_test_split(features, labels, train_size=i)
        gamma = [0.000001,0.000005,0.00005,0.0001,0.001]
        C = [0.01,0.1,1.0,10,100]
        for k in gamma:
            for l in C:
                clf_grid = svm.SVC(kernel='rbf',gamma=k,C=l)
                clf_grid.fit(X_train, y_train)
                y_pred = clf_grid.predict(X_test)
                y_pred_test = clf_grid.predict(np_test)
                print("For sample:",j, " For gamma:", k," for C:",l)
                print("***Validation accuracy***")
                print(accuracy_score(y_test, y_pred))
                print("***Test accuracy***")
                print(accuracy_score(np_test_labels, y_pred_test))

For sample: 1  For gamma: 1e-06  for C: 0.01
***Validation accuracy***
0.8567658081762175
***Test accuracy***
0.7564919322253051
For sample: 1  For gamma: 1e-06  for C: 0.1
***Validation accuracy***
0.8697597555988875
***Test accuracy***
0.7784459768876438
For sample: 1  For gamma: 1e-06  for C: 1.0
***Validation accuracy***
0.8811045362225294
***Test accuracy***
0.8024338011475366
For sample: 1  For gamma: 1e-06  for C: 10
***Validation accuracy***
0.8904148938686817
***Test accuracy***
0.8109797160789807
For sample: 1  For gamma: 1e-06  for C: 100
***Validation accuracy***
0.8971129442696523
***Test accuracy***
0.8195795059666514
For sample: 1  For gamma: 5e-06  for C: 0.01
***Validation accuracy***
0.8736697678662553
***Test accuracy***
0.79184737224901
For sample: 1  For gamma: 5e-06  for C: 0.1
***Validation accuracy***
0.888982011240018
***Test accuracy***
0.8098079357810521
For sample: 1  For gamma: 5e-06  for C: 1.0
***Validation accuracy***
0.899728630954996
***Test accuracy**

In [11]:
# Pandas is used for data manipulation
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score,train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_recall_fscore_support, f1_score, roc_curve, roc_auc_score, RocCurveDisplay, auc
from collections import Counter
from sklearn import preprocessing
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

def convert(data):
    number = preprocessing.LabelEncoder()
    data['operator'] = number.fit_transform(data.operator)
    data['methodReturn'] = number.fit_transform(data.methodReturn)
    data['isKilled'] = number.fit_transform(data.isKilled)
    return data

# Read in data and display first 5 rows
features = pd.read_csv('py_files/training_data.csv',encoding= 'unicode_escape')
#print(features)
#print('The shape of our features is:', features.shape)

#Convert string to float
features=convert(features)
#print(features)
#print('The shape of our features is:', features.shape) 

# Use numpy to convert to arrays
# Labels are the values we want to predict
np_labels = np.array(features['isKilled'])
# Remove the labels from the features
# axis 1 refers to the columns
features= features.drop('isKilled', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)

new_features= features.drop('DepthTree', axis = 1)
new_features= new_features.drop('methodReturn', axis = 1)
new_features= new_features.drop('DepthNested', axis = 1)
new_features= new_features.drop('mutantAssert', axis = 1)
print('The shape of our features is:', new_features.shape)
# Convert to numpy array
np_features = np.array(new_features)
X_train, X_test, y_train, y_test = train_test_split(np_features, np_labels, test_size=0.5)
clf = svm.SVC(kernel='rbf',gamma=0.000005,C=10)
clf.fit(X_train, y_train)
y_pred_train = clf.predict(X_test)
print(accuracy_score(y_test, y_pred_train))
print(confusion_matrix(y_test, y_pred_train))

The shape of our features is: (591813, 10)
0.9069707712220394
[[225338   9845]
 [ 17683  43041]]


In [12]:
test = pd.read_csv('py_files/testing_data.csv',encoding= 'unicode_escape')

#Convert string to float
test=convert(test)

# ## Labels are the values we want to predict
np_test_labels = np.array(test['isKilled'])

# # Remove the labels from the features
# # axis 1 refers to the columns
test= test.drop('isKilled', axis = 1)

# # Saving feature names for later use
feature_list = list(test.columns)

new_test= test.drop('DepthTree', axis = 1)
new_test= new_test.drop('methodReturn', axis = 1)
new_test= new_test.drop('DepthNested', axis = 1)
new_test= new_test.drop('mutantAssert', axis = 1)
# # Convert to numpy array
np_test = np.array(test)



print('The shape of our features is:', new_test.shape) 
# # Convert to numpy array
np_test = np.array(new_test)
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)
print(precision_recall_fscore_support(np_test_labels, y_pred_test, average='micro'))
print(f1_score(np_test_labels, y_pred_test, average='micro'))

The shape of our features is: (148492, 10)
0.8311760902944266
Confusion_matrix:
 [[84882  8100]
 [16969 38541]]
(0.8311760902944266, 0.8311760902944266, 0.8311760902944266, None)
0.8311760902944266


In [22]:
from sklearn.preprocessing import Normalizer
# Pandas is used for data manipulation
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score,train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_recall_fscore_support, f1_score, roc_curve, roc_auc_score, RocCurveDisplay, auc
from collections import Counter
from sklearn import preprocessing
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm

def convert(data):
    number = preprocessing.LabelEncoder()
    data['operator'] = number.fit_transform(data.operator)
    data['methodReturn'] = number.fit_transform(data.methodReturn)
    data['isKilled'] = number.fit_transform(data.isKilled)
    return data

# Read in data and display first 5 rows
features = pd.read_csv('py_files/training_data.csv',encoding= 'unicode_escape')
#print(features)
#print('The shape of our features is:', features.shape)

#Convert string to float
features=convert(features)
#print(features)
#print('The shape of our features is:', features.shape) 

# Use numpy to convert to arrays
# Labels are the values we want to predict
np_labels = np.array(features['isKilled'])
# Remove the labels from the features
# axis 1 refers to the columns
features= features.drop('isKilled', axis = 1)
# Saving feature names for later use
feature_list = list(features.columns)

transformer = Normalizer().fit(features)
features = transformer.transform(features)
print('The shape of our features is:', features.shape)
# Convert to numpy array
np_features = np.array(features)
X_train, X_test, y_train, y_test = train_test_split(np_features, np_labels, test_size=0.5)
clf = svm.SVC(kernel='rbf',gamma=0.00005,C=10)
clf.fit(X_train, y_train)
y_pred_train = clf.predict(X_test)
print(accuracy_score(y_test, y_pred_train))
print(confusion_matrix(y_test, y_pred_train))

The shape of our features is: (591813, 14)
0.8937132274667379
[[225600   9580]
 [ 21871  38856]]


### Testing using normalized data for svm

In [23]:
test = pd.read_csv('py_files/testing_data.csv',encoding= 'unicode_escape')

#Convert string to float
test=convert(test)

# ## Labels are the values we want to predict
np_test_labels = np.array(test['isKilled'])

# # Remove the labels from the features
# # axis 1 refers to the columns
test= test.drop('isKilled', axis = 1)

# # Saving feature names for later use
feature_list = list(test.columns)


# # Convert to numpy array
np_test = np.array(test)


transformer = Normalizer().fit(test)
test = transformer.transform(test)
print('The shape of our features is:', test.shape) 
# # Convert to numpy array
np_test = np.array(test)
y_pred_test = clf.predict(np_test)
#print("Predicted labels::", y_pred_test)
print(accuracy_score(np_test_labels, y_pred_test))
confusion = confusion_matrix(np_test_labels, y_pred_test)
print("Confusion_matrix:\n",confusion)
print(precision_recall_fscore_support(np_test_labels, y_pred_test, average='micro'))
print(f1_score(np_test_labels, y_pred_test, average='micro'))

The shape of our features is: (148492, 14)
0.7567882444845514
Confusion_matrix:
 [[87890  5092]
 [31023 24487]]
(0.7567882444845514, 0.7567882444845514, 0.7567882444845514, None)
0.7567882444845514


In [26]:
##Validation set create training and testing vars
size = [0.5]
for i in size:
    validation_accuracy  = 0.0
    test_accuracy = 0.0
    for j in range(1):
        X_train, X_test, y_train, y_test = train_test_split(np_features, np_labels, train_size=i)
        gamma = [0.000001,0.000005,0.00005,0.0001,0.001]
        C = [0.01,0.1,1.0,10,100]
        for k in gamma:
            for l in C:
                clf_grid = svm.SVC(kernel='rbf',gamma=k,C=l)
                clf_grid.fit(X_train, y_train)
                y_pred = clf_grid.predict(X_test)
                y_pred_test = clf_grid.predict(np_test)
                print("For sample:",j, " For gamma:", k," for C:",l)
                print("***Validation accuracy***")
                print(accuracy_score(y_test, y_pred))
                print("***Test accuracy***")
                print(accuracy_score(np_test_labels, y_pred_test))

For sample: 0  For gamma: 1e-06  for C: 0.01
***Validation accuracy***
0.7948612232897498
***Test accuracy***
0.6261751474826927
For sample: 0  For gamma: 1e-06  for C: 0.1
***Validation accuracy***
0.7948612232897498
***Test accuracy***
0.6261751474826927
For sample: 0  For gamma: 1e-06  for C: 1.0
***Validation accuracy***
0.7948612232897498
***Test accuracy***
0.6261751474826927
For sample: 0  For gamma: 1e-06  for C: 10
***Validation accuracy***
0.7948612232897498
***Test accuracy***
0.6261751474826927
For sample: 0  For gamma: 1e-06  for C: 100
***Validation accuracy***
0.8882081194429331
***Test accuracy***
0.7500673436952833
For sample: 0  For gamma: 5e-06  for C: 0.01
***Validation accuracy***
0.7948612232897498
***Test accuracy***
0.6261751474826927
For sample: 0  For gamma: 5e-06  for C: 0.1
***Validation accuracy***
0.7948612232897498
***Test accuracy***
0.6261751474826927
For sample: 0  For gamma: 5e-06  for C: 1.0
***Validation accuracy***
0.7948612232897498
***Test accura

In [27]:
##Validation set create training and testing vars
size = [0.5]
for i in size:
    validation_accuracy  = 0.0
    test_accuracy = 0.0
    for j in range(1):
        X_train, X_test, y_train, y_test = train_test_split(np_features, np_labels, train_size=i)
        gamma = [0.005,0.01,0.05,0.1,0.5]
        C = [0.01,0.1,1.0,10,100]
        for k in gamma:
            for l in C:
                clf_grid = svm.SVC(kernel='rbf',gamma=k,C=l)
                clf_grid.fit(X_train, y_train)
                y_pred = clf_grid.predict(X_test)
                y_pred_test = clf_grid.predict(np_test)
                print("For sample:",j, " For gamma:", k," for C:",l)
                print("***Validation accuracy***")
                print(accuracy_score(y_test, y_pred))
                print("***Test accuracy***")
                print(accuracy_score(np_test_labels, y_pred_test))

For sample: 0  For gamma: 0.005  for C: 0.01
***Validation accuracy***
0.8852815242626907
***Test accuracy***
0.7475150176440482
For sample: 0  For gamma: 0.005  for C: 0.1
***Validation accuracy***
0.8947371978358065
***Test accuracy***
0.7563976510519085
For sample: 0  For gamma: 0.005  for C: 1.0
***Validation accuracy***
0.9035440188978294
***Test accuracy***
0.7616706623925869
For sample: 0  For gamma: 0.005  for C: 10
***Validation accuracy***
0.9099277813637393
***Test accuracy***
0.7728227783314926
For sample: 0  For gamma: 0.005  for C: 100
***Validation accuracy***
0.92027900657977
***Test accuracy***
0.7878269536406002
For sample: 0  For gamma: 0.01  for C: 0.01
***Validation accuracy***
0.8883669531305444
***Test accuracy***
0.7499932656304716
For sample: 0  For gamma: 0.01  for C: 0.1
***Validation accuracy***
0.8982450567239031
***Test accuracy***
0.757818603022385
For sample: 0  For gamma: 0.01  for C: 1.0
***Validation accuracy***
0.9062948831896508
***Test accuracy***


In [28]:
##Validation set create training and testing vars
size = [0.5]
for i in size:
    validation_accuracy  = 0.0
    test_accuracy = 0.0
    for j in range(1):
        X_train, X_test, y_train, y_test = train_test_split(np_features, np_labels, train_size=i)
        gamma = [1,5,10]
        C = [0.01,0.1,1.0,10,100]
        for k in gamma:
            for l in C:
                clf_grid = svm.SVC(kernel='rbf',gamma=k,C=l)
                clf_grid.fit(X_train, y_train)
                y_pred = clf_grid.predict(X_test)
                y_pred_test = clf_grid.predict(np_test)
                print("For sample:",j, " For gamma:", k," for C:",l)
                print("***Validation accuracy***")
                print(accuracy_score(y_test, y_pred))
                print("***Test accuracy***")
                print(accuracy_score(np_test_labels, y_pred_test))

For sample: 0  For gamma: 1  for C: 0.01
***Validation accuracy***
0.9200728607298915
***Test accuracy***
0.7845136438326644
For sample: 0  For gamma: 1  for C: 0.1
***Validation accuracy***
0.930670785077744
***Test accuracy***
0.8018344422595156
For sample: 0  For gamma: 1  for C: 1.0
***Validation accuracy***
0.9375006336450303
***Test accuracy***
0.8166163833741885
For sample: 0  For gamma: 1  for C: 10
***Validation accuracy***
0.940768552281629
***Test accuracy***
0.827532796379603
For sample: 0  For gamma: 1  for C: 100
***Validation accuracy***
0.9442020634861629
***Test accuracy***
0.8190272876653287
For sample: 0  For gamma: 5  for C: 0.01
***Validation accuracy***
0.9251014676908623
***Test accuracy***
0.7930460900250519
For sample: 0  For gamma: 5  for C: 0.1
***Validation accuracy***
0.9380481029512651
***Test accuracy***
0.8154378687067316
For sample: 0  For gamma: 5  for C: 1.0
***Validation accuracy***
0.9436917680217095
***Test accuracy***
0.8294049511084772
For sample

### Normalization for sigmoid kernel

In [30]:
##Validation set create training and testing vars
size = [0.5]
for i in size:
    validation_accuracy  = 0.0
    test_accuracy = 0.0
    for j in range(1):
        X_train, X_test, y_train, y_test = train_test_split(np_features, np_labels, train_size=i)
        coeff = [0.01,0.1,0,1.0,10]
        C = [0.01,0.1,1.0,10,100]
        for k in coeff:
            for l in C:
                clf_grid = svm.SVC(kernel='sigmoid',coef0=k,C=l)
                clf_grid.fit(X_train, y_train)
                y_pred = clf_grid.predict(X_test)
                y_pred_test = clf_grid.predict(np_test)
                print("For sample:",j, " For coeff:", k," for C:",l)
                print("***Validation accuracy***")
                print(accuracy_score(y_test, y_pred))
                print("***Test accuracy***")
                print(accuracy_score(np_test_labels, y_pred_test))

For sample: 0  For coeff: 0.01  for C: 0.01
***Validation accuracy***
0.8320452033916061
***Test accuracy***
0.7415955068286507
For sample: 0  For coeff: 0.01  for C: 0.1
***Validation accuracy***
0.8034314835404367
***Test accuracy***
0.777476227675565
For sample: 0  For coeff: 0.01  for C: 1.0
***Validation accuracy***
0.8013125745588986
***Test accuracy***
0.7768297282008458
For sample: 0  For coeff: 0.01  for C: 10
***Validation accuracy***
0.801109808149182
***Test accuracy***
0.7766209627454678
For sample: 0  For coeff: 0.01  for C: 100
***Validation accuracy***
0.8010827726278865
***Test accuracy***
0.7766142283759394
For sample: 0  For coeff: 0.1  for C: 0.01
***Validation accuracy***
0.8314166275214848
***Test accuracy***
0.7412991945694044
For sample: 0  For coeff: 0.1  for C: 0.1
***Validation accuracy***
0.8014274755244046
***Test accuracy***
0.7766546345931093
For sample: 0  For coeff: 0.1  for C: 1.0
***Validation accuracy***
0.7991936655773605
***Test accuracy***
0.77698